name: Test gha-trivy Action

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Create dummy file to scan
        run: |
          echo 'FROM alpine' > Dockerfile
          echo 'RUN apk add --no-cache curl' >> Dockerfile

      - name: Build test image
        run: |
          docker build -t test-gha-trivy:latest .

      - name: Run gha-trivy action
        uses: ./
        with:
          image-ref: test-gha-trivy:latest
          create-test-report: "true"
          create-summary: "true"
