name: Check Conventions

on:
  pull_request:

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Set up mise
        uses: jdx/mise-action@v2

      - name: Check conventions with hk
        run: |
          hk check --all || { echo 'Convention check failed!'; exit 1; }
