name: Check Conventions

on:
  pull_request:

jobs:
  check-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up mise
        uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2

      - name: Check conventions with hk
        run: |
          hk check --all || { echo 'Convention check failed!'; exit 1; }
